export const countryCodes = [
    { name: "United States", code: "+1", flag: "🇺🇸" },
    { name: "Canada", code: "+1", flag: "🇨🇦" },
    { name: "United Kingdom", code: "+44", flag: "🇬🇧" },
    { name: "Australia", code: "+61", flag: "🇦🇺" },
    { name: "New Zealand", code: "+64", flag: "🇳🇿" },
    { name: "India", code: "+91", flag: "🇮🇳" },
    { name: "China", code: "+86", flag: "🇨🇳" },
    { name: "Japan", code: "+81", flag: "🇯🇵" },
    { name: "Germany", code: "+49", flag: "🇩🇪" },
    { name: "France", code: "+33", flag: "🇫🇷" },
    { name: "Italy", code: "+39", flag: "🇮🇹" },
    { name: "Spain", code: "+34", flag: "🇪🇸" },
    { name: "South Africa", code: "+27", flag: "🇿🇦" },
    { name: "Brazil", code: "+55", flag: "🇧🇷" },
    { name: "Argentina", code: "+54", flag: "🇦🇷" },
    { name: "Mexico", code: "+52", flag: "🇲🇽" },
    { name: "Russia", code: "+7", flag: "🇷🇺" },
    { name: "Nigeria", code: "+234", flag: "🇳🇬" },
    { name: "Egypt", code: "+20", flag: "🇪🇬" },
    { name: "Saudi Arabia", code: "+966", flag: "🇸🇦" },
    { name: "Turkey", code: "+90", flag: "🇹🇷" },
    { name: "Netherlands", code: "+31", flag: "🇳🇱" },
    { name: "Belgium", code: "+32", flag: "🇧🇪" },
    { name: "Poland", code: "+48", flag: "🇵🇱" },
    { name: "Sweden", code: "+46", flag: "🇸🇪" },
    { name: "Norway", code: "+47", flag: "🇳🇴" },
    { name: "Denmark", code: "+45", flag: "🇩🇰" },
    { name: "Finland", code: "+358", flag: "🇫🇮" },
    { name: "Switzerland", code: "+41", flag: "🇨🇭" },
    { name: "Austria", code: "+43", flag: "🇦🇹" },
    { name: "Greece", code: "+30", flag: "🇬🇷" },
    { name: "Portugal", code: "+351", flag: "🇵🇹" },
    { name: "Czech Republic", code: "+420", flag: "🇨🇿" },
    { name: "Romania", code: "+40", flag: "🇷🇴" },
    { name: "Hungary", code: "+36", flag: "🇭🇺" },
    { name: "Ireland", code: "+353", flag: "🇮🇪" },
    { name: "Croatia", code: "+385", flag: "🇭🇷" },
    { name: "Slovenia", code: "+386", flag: "🇸🇮" },
    { name: "Slovakia", code: "+421", flag: "🇸🇰" },
    { name: "Bulgaria", code: "+359", flag: "🇧🇬" },
    { name: "Lithuania", code: "+370", flag: "🇱🇹" },
    { name: "Latvia", code: "+371",  },
    { name: "Estonia", code: "+372", flag: "🇪🇪" },
    { name: "Cyprus", code: "+357", flag: "🇨🇾" },
    { name: "Luxembourg", code: "+352", flag: "🇱🇺" },
    { name: "Malta", code: "+356", flag: "🇲🇹" },
    { name: "Iceland", code: "+354", flag: "🇮🇸" },
    { name: "Finland", code: "+358", flag: "🇫🇮" },
    { name: "Norway", code: "+47", flag: "🇳🇴" },
    { name: "Sweden", code: "+46", flag: "🇸🇪" },
    { name: "Denmark", code: "+45", flag: "🇩🇰" },
    { name: "Ukraine", code: "+380", flag: "🇺🇦" },
    { name: "Belarus", code: "+375", flag: "🇧🇾" },
    { name: "Moldova", code: "+373", flag: "🇲🇩" },
    { name: "Romania", code: "+40", flag: "🇷🇴" },
    { name: "Bulgaria", code: "+359", flag: "🇧🇬" },
    { name: "Serbia", code: "+381", flag: "🇷🇸" },
    { name: "Montenegro", code: "+382", flag: "🇲🇪" },
    { name: "Kosovo", code: "+383", flag: "🇽🇰" },
    { name: "Croatia", code: "+385", flag: "🇭🇷" },
    { name: "Slovenia", code: "+386", flag: "🇸🇮" },
    { name: "Bosnia and Herzegovina", code: "+387", flag: "🇧🇦" },
    { name: "Macedonia", code: "+389", flag: "🇲🇰" },
    { name: "Czech Republic", code: "+420", flag: "🇨🇿" },
    { name: "Slovakia", code: "+421", flag: "🇸🇰" },
    { name: "Liechtenstein", code: "+423", flag: "🇱🇮" },
    { name: "Falkland Islands", code: "+500", flag: "🇫🇰" },
    { name: "Belize", code: "+501", flag: "🇧🇿" },
    { name: "Guatemala", code: "+502", flag: "🇬🇹" },
    { name: "El Salvador", code: "+503", flag: "🇸🇻" },
    { name: "Honduras", code: "+504", flag: "🇭🇳" },
    { name: "Nicaragua", code: "+505", flag: "🇳🇮" },
    { name: "Costa Rica", code: "+506", flag: "🇨🇷" },
    { name: "Panama", code: "+507", flag: "🇵🇦" },
    { name: "Haiti", code: "+509", flag: "🇭🇹" },
    { name: "Peru", code: "+51", flag: "🇵🇪" },
    { name: "Mexico", code: "+52", flag: "🇲🇽" },
    { name: "Cuba", code: "+53", flag: "🇨🇺" },
    { name: "Argentina", code: "+54", flag: "🇦🇷" },
    { name: "Brazil", code: "+55", flag: "🇧🇷" },
    { name: "Chile", code: "+56", flag: "🇨🇱" },
    { name: "Colombia", code: "+57", flag: "🇨🇴" },
    { name: "Venezuela", code: "+58", flag: "🇻🇪" },
    { name: "Malaysia", code: "+60", flag: "🇲🇾" },
    { name: "Australia", code: "+61", flag: "🇦🇺" },
    { name: "Indonesia", code: "+62", flag: "🇮🇩" },
    { name: "Philippines", code: "+63", flag: "🇵🇭" },
    { name: "New Zealand", code: "+64", flag: "🇳🇿" },
    { name: "Singapore", code: "+65", flag: "🇸🇬" },
    { name: "Thailand", code: "+66", flag: "🇹🇭" },
    { name: "Japan", code: "+81", flag: "🇯🇵" },
    { name: "South Korea", code: "+82", flag: "🇰🇷" },
    { name: "Vietnam", code: "+84", flag: "🇻🇳" },
    { name: "China", code: "+86", flag: "🇨🇳" },
    { name: "Turkey", code: "+90", flag: "🇹🇷" },
    { name: "India", code: "+91", flag: "🇮🇳" },
    { name: "Pakistan", code: "+92", flag: "🇵🇰" },
    { name: "Afghanistan", code: "+93", flag: "🇦🇫" },
    { name: "Sri Lanka", code: "+94", flag: "🇱🇰" },
    { name: "Myanmar", code: "+95", flag: "🇲🇲" },
    { name: "Iran", code: "+98", flag: "🇮🇷" },
    { name: "Morocco", code: "+212", flag: "🇲🇦" },
    { name: "Algeria", code: "+213", flag: "🇩🇿" },
    { name: "Tunisia", code: "+216", flag: "🇹🇳" },
    { name: "Libya", code: "+218", flag: "🇱🇾" },
    { name: "Gambia", code: "+220", flag: "🇬🇲" },
    { name: "Senegal", code: "+221", flag: "🇸🇳" },
    { name: "Mauritania", code: "+222", flag: "🇲🇷" },
    { name: "Mali", code: "+223", flag: "🇲🇱" },
    { name: "Guinea", code: "+224", flag: "🇬🇳" },
    { name: "Ivory Coast", code: "+225", flag: "🇨🇮" },
    { name: "Burkina Faso", code: "+226", flag: "🇧🇫" },
    { name: "Niger", code: "+227", flag: "🇳🇪" },
    { name: "Togo", code: "+228", flag: "🇹🇬" },
    { name: "Benin", code: "+229", flag: "🇧🇯" },
    { name: "Mauritius", code: "+230", flag: "🇲🇺" },
    { name: "Liberia", code: "+231", flag: "🇱🇷" },
    { name: "Sierra Leone", code: "+232", flag: "🇸🇱" },
    { name: "Ghana", code: "+233", flag: "🇬🇭" },
    { name: "Nigeria", code: "+234", flag: "🇳🇬" },
    { name: "Chad", code: "+235", flag: "🇹🇩" },
    { name: "Central African Republic", code: "+236", flag: "🇨🇫" },
    { name: "Cameroon", code: "+237", flag: "🇨🇲" },
    { name: "Bolivia", code: "+591", flag: "🇧🇴" },
    { name: "Guyana", code: "+592", flag: "🇬🇾" },
    { name: "Ecuador", code: "+593", flag: "🇪🇨" },
    { name: "Paraguay", code: "+595", flag: "🇵🇾" },
    { name: "Suriname", code: "+597", flag: "🇸🇷" },
    { name: "Uruguay", code: "+598", flag: "🇺🇾" },
    { name: "Malaysia", code: "+60", flag: "🇲🇾" },
    { name: "Australia", code: "+61", flag: "🇦🇺" },
    { name: "Indonesia", code: "+62", flag: "🇮🇩" },
    { name: "Philippines", code: "+63", flag: "🇵🇭" },
    { name: "New Zealand", code: "+64", flag: "🇳🇿" },
    { name: "Singapore", code: "+65", flag: "🇸🇬" },
    { name: "Thailand", code: "+66", flag: "🇹🇭" },
    { name: "East Timor", code: "+670", flag: "🇹🇱" },
    { name: "Brunei", code: "+673", flag: "🇧🇳" },
    { name: "Nauru", code: "+674", flag: "🇳🇷" },
    { name: "Papua New Guinea", code: "+675", flag: "🇵🇬" },
    { name: "Tonga", code: "+676", flag: "🇹🇴" },
    { name: "Solomon Islands", code: "+677", flag: "🇸🇧" },
    { name: "Vanuatu", code: "+678", flag: "🇻🇺" },
    { name: "Fiji", code: "+679", flag: "🇫🇯" },
    { name: "Palau", code: "+680", flag: "🇵🇼" },
    { name: "Wallis and Futuna", code: "+681", flag: "🇼🇫" },
    { name: "Cook Islands", code: "+682", flag: "🇨🇰" },
    { name: "Niue", code: "+683", flag: "🇳🇺" },
    { name: "Samoa", code: "+685", flag: "🇼🇸" },
    { name: "Kiribati", code: "+686", flag: "🇰🇮" },
    { name: "New Caledonia", code: "+687", flag: "🇳🇨" },
    { name: "Tuvalu", code: "+688", flag: "🇹🇻" },
    { name: "French Polynesia", code: "+689", flag: "🇵🇫" },
    { name: "Tokelau", code: "+690", flag: "🇹🇰" },
    { name: "Micronesia", code: "+691", flag: "🇫🇲" },
    { name: "Marshall Islands", code: "+692", flag: "🇲🇭" },
    { name: "Kazakhstan", code: "+7", flag: "🇰🇿" },
    { name: "Russia", code: "+7", flag: "🇷🇺" },
    { name: "Japan", code: "+81", flag: "🇯🇵" },
    { name: "South Korea", code: "+82", flag: "🇰🇷" },
    { name: "Vietnam", code: "+84", flag: "🇻🇳" },
    { name: "North Korea", code: "+850", flag: "🇰🇵" },
    { name: "Hong Kong", code: "+852", flag: "🇭🇰" },
    { name: "Macau", code: "+853", flag: "🇲🇴" },
    { name: "Cambodia", code: "+855", flag: "🇰🇭" },
    { name: "Laos", code: "+856", flag: "🇱🇦" },
    { name: "Bangladesh", code: "+880", flag: "🇧🇩" },
    { name: "Taiwan", code: "+886", flag: "🇹🇼" },
    { name: "Maldives", code: "+960", flag: "🇲🇻" },
    { name: "Lebanon", code: "+961", flag: "🇱🇧" },
    { name: "Jordan", code: "+962", flag: "🇯🇴" },
    { name: "Syria", code: "+963", flag: "🇸🇾" },
    { name: "Iraq", code: "+964", flag: "🇮🇶" },
    { name: "Kuwait", code: "+965", flag: "🇰🇼" },
    { name: "Saudi Arabia", code: "+966", flag: "🇸🇦" },
    { name: "Yemen", code: "+967", flag: "🇾🇪" },
    { name: "Oman", code: "+968", flag: "🇴🇲" },
    { name: "Palestine", code: "+970", flag: "🇵🇸" },
    { name: "United Arab Emirates", code: "+971", flag: "🇦🇪" },
    { name: "Israel", code: "+972", flag: "🇮🇱" },
    { name: "Bahrain", code: "+973", flag: "🇧🇭" },
    { name: "Qatar", code: "+974", flag: "🇶🇦" },
    { name: "Bhutan", code: "+975", flag: "🇧🇹" },
    { name: "Mongolia", code: "+976", flag: "🇲🇳" },
    { name: "Nepal", code: "+977", flag: "🇳🇵" },
    { name: "Iran", code: "+98", flag: "🇮🇷" },
    { name: "Tajikistan", code: "+992", flag: "🇹🇯" },
    { name: "Turkmenistan", code: "+993", flag: "🇹🇲" },
    { name: "Azerbaijan", code: "+994", flag: "🇦🇿" },
    { name: "Georgia", code: "+995", flag: "🇬🇪" },
    { name: "Kyrgyzstan", code: "+996", flag: "🇰🇬" },
    { name: "Uzbekistan", code: "+998", flag: "🇺🇿" },
  ];