/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "saigeAppAPI",
            "endpoint": "https://c656jkreu4.execute-api.us-east-1.amazonaws.com/saige",
            "region": "us-east-1"
        },
        {
            "name": "saigeAPP1API",
            "endpoint": "https://xjf1zya1yg.execute-api.us-east-1.amazonaws.com/saige",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:604bef63-31cb-446e-bbee-5c1d01821a04",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Uk1vQcGqI",
    "aws_user_pools_web_client_id": "4hj2e3u5q2nqhcr93eqb4a508i",
    "oauth": {
        "domain": "saigeapp1ea3aa9b1-ea3aa9b1-saige.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://example.com/auth/",
        "redirectSignOut": "https://example.com/auth/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
